query = from(bucket: "power_consumption") 
                |> range(start: {start_time}, stop: {stop_time})
                |> filter(fn: (r) => r["_measurement"] == "power_consumption")
                |> filter(fn: (r) => r["_field"] == "power")
                |> filter(fn: (r) => r["sensor"] == "{sensor}")
                |> filter(fn: (r) => r["target"] == "{container_name}")
                |> keep(columns: ["_time", "_field", "_value"])
                |> pivot(rowKey:["_time"], columnKey: ["_field"], valueColumn: "_value")
                |> yield()